name: Setup
description: Sets up Ruby and installs dependencies with Bundler

inputs:
  ruby-version:
    description: Ruby version to use
    default: '3.2.2'
  install-gem-release:
    description: Whether to install the `gem-release` gem
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install
      shell: bash

    - name: Install `gem release`
      if: ${{ inputs.install-gem-release == 'true' }}
      run: gem install gem-release
      shell: bash
