name: Publish

on:
  workflow_dispatch:
    inputs:
      gem_version_level:
        required: true
        description: 'Gem version level (major, minor, patch)'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

env:
  RUBY_VERSION: '3.2.2'

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          install-gem-release: 'true'

      - name: Setup Git user
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Bump version
        run: |
          gem bump --version ${{ github.event.inputs.gem_version_level }}
          git push --tags origin

  # publish-rubygems:
  #   name: Publish to RubyGems
  #   runs-on: ubuntu-latest
  #   needs: bump-version

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup
  #       uses: ./.github/actions/setup
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #         install-gem-release: 'true'

  #     - name: Setup credentials
  #       uses: ./.github/actions/credentials
  #       with:
  #         gem-host-api-key: ${{ secrets.RUBYGEMS_API_KEY }}

  #     - name: Release to RubyGems
  #       run: gem release

  publish-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          install-gem-release: 'true'

      - name: Setup credentials
        uses: ./.github/actions/credentials
        with:
          gem-host-api-key: 'Bearer ${{secrets.GITHUB_TOKEN}}'

      - name: Push to GitHub Packages
        run: gem release --github
